name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"
        id: go



      - name: Build and Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean 
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
